// Tests for entity resolution — verifies that generated REPORT.md and
// source README.md resolve to different detail models and never
// overwrite each other.

import { describe, expect, it } from 'vitest';
import {
  buildInOutViewModel,
  buildReportDetail,
  buildDocumentDetail,
  getSummary,
} from './inOut';
import { experiments, findings, openQuestions, edges } from './index';

const exp = experiments.find((e) => e.slug === 'experiments/2026-06-08_anomaly_check')!;

describe('ReportDetail entity resolution', () => {
  const detail = buildReportDetail(exp, 'generated-report');

  it('has kind = report (not document)', () => {
    expect(detail.kind).toBe('report');
  });

  it('has title REPORT.md (not README.md)', () => {
    expect(detail.title).toBe('REPORT.md');
    expect(detail.title).not.toBe('README.md');
  });

  it('has relationshipToCurrent saying "Generated by"', () => {
    expect(detail.relationshipToCurrent).toContain('Generated by');
  });

  it('does not say "Source document"', () => {
    expect(detail.relationshipToCurrent).not.toContain('Source document');
  });

  it('has an "Open report" action (not "Open document")', () => {
    expect(detail.actions[0].label).toBe('Open report');
    expect(detail.actions[0].label).not.toBe('Open document');
  });
});

describe('DocumentDetail entity resolution', () => {
  const detail = buildDocumentDetail(exp, 'source-document');

  it('has kind = document (not report)', () => {
    expect(detail.kind).toBe('document');
  });

  it('has title README.md (not REPORT.md)', () => {
    expect(detail.title).toBe('README.md');
    expect(detail.title).not.toBe('REPORT.md');
  });

  it('has relationshipToCurrent saying "Source document"', () => {
    expect(detail.relationshipToCurrent).toContain('Source document');
  });

  it('has an "Open document" action', () => {
    expect(detail.actions[0].label).toBe('Open document');
  });
});

describe('Report and Document never share canonical key', () => {
  const reportDetail = buildReportDetail(exp, 'generated-report');
  const docDetail = buildDocumentDetail(exp, 'source-document');

  it('report kind !== document kind', () => {
    expect(reportDetail.kind).not.toBe(docDetail.kind);
  });

  it('report title !== document title', () => {
    expect(reportDetail.title).not.toBe(docDetail.title);
  });
});

describe('Multiple experiments have independent REPORT.md', () => {
  const exp2 = experiments.find((e) => e.slug === 'experiments/2026-05-20_feed_rate_recheck')!;
  if (exp2.reportStatus === 'report') {
    const detail1 = buildReportDetail(exp, 'generated-report');
    const detail2 = buildReportDetail(exp2, 'generated-report');

    it('both have kind = report', () => {
      expect(detail1.kind).toBe('report');
      expect(detail2.kind).toBe('report');
    });

    it('they reference different experiments', () => {
      expect(detail1.sourceExperiment).not.toBe(detail2.sourceExperiment);
    });
  }
});

describe('View model report output', () => {
  const vm = buildInOutViewModel({
    experiments, findings, openQuestions, edges,
    focusSlug: 'experiments/2026-06-08_anomaly_check',
  });

  it('has a generated-report output', () => {
    const reportOutput = vm.outputs.find((o) => o.role === 'generated-report');
    expect(reportOutput).toBeTruthy();
  });

  it('report output has kind = report in entity', () => {
    const reportOutput = vm.outputs.find((o) => o.role === 'generated-report');
    expect(reportOutput!.entity.kind).toBe('report');
  });

  it('report output entity title is REPORT.md', () => {
    const reportOutput = vm.outputs.find((o) => o.role === 'generated-report');
    expect(reportOutput!.entity.title).toBe('REPORT.md');
  });

  it('report output entity id contains "report:"', () => {
    const reportOutput = vm.outputs.find((o) => o.role === 'generated-report');
    expect(reportOutput!.entity.id).toContain('report:');
  });

  it('document input entity title is README.md', () => {
    const docInput = vm.inputs.find((i) => i.role === 'source-document');
    expect(docInput).toBeTruthy();
    expect(docInput!.entity.title).toBe('README.md');
  });

  it('document input entity kind is document (not report)', () => {
    const docInput = vm.inputs.find((i) => i.role === 'source-document');
    expect(docInput!.entity.kind).toBe('document');
  });
});

describe('Summary formatting', () => {
  const vm = buildInOutViewModel({
    experiments, findings, openQuestions, edges,
    focusSlug: 'experiments/2026-06-08_anomaly_check',
  });
  const summary = getSummary(vm);

  it('generatedReport is a boolean', () => {
    expect(typeof summary.generatedReport).toBe('boolean');
  });

  it('generatedReport is true when report exists', () => {
    expect(summary.generatedReport).toBe(true);
  });

  it('artifacts is a number', () => {
    expect(typeof summary.artifacts).toBe('number');
  });

  it('connections is a number', () => {
    expect(typeof summary.connections).toBe('number');
  });
});
