// In/Out view model — entity-specific detail models.
//
// Design rules:
// 1. Each entity type has its own detail view model with typed fields —
//    no generic key/value pairs passed to the UI.
// 2. Confidence is never labeled as "status".
// 3. Artifact filenames are never labeled as "status".
// 4. Raw internal routes are never rendered as primary content.
// 5. Actions are generated by entity type — never reused across
//    incompatible types.
// 6. The same finding ID must not appear as both an input and an output
//    without an explicit role.
// 7. Relationship endpoints resolve to real entities — no silent
//    fallback to the experiment title.

import type { Edge, EdgeType, Experiment, Finding, OpenQuestion } from './types';
import { canonicalExperimentPath } from './routes';

// ── Entity kinds ────────────────────────────────────────────────────────

export type InOutEntityKind = 'finding' | 'question' | 'experiment' | 'dataset' | 'document' | 'artifact' | 'unknown';

// ── Detail action ───────────────────────────────────────────────────────

export interface InOutDetailAction {
  label: string;
  href: string;
  icon?: 'open' | 'preview' | 'inspect';
}

// ── Entity-specific detail view models ──────────────────────────────────

export interface FindingDetail {
  kind: 'finding';
  role: string;
  title: string;
  id: string;
  summary: string;
  confidence: string;
  category: string;
  actionStatus: string;
  date: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface QuestionDetail {
  kind: 'question';
  role: string;
  title: string;
  id: string;
  summary: string;
  status: string;
  priority: string;
  area: string;
  raisedDate: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface DatasetDetail {
  kind: 'dataset';
  role: string;
  title: string;
  id: string;
  rowCount: string;
  dateRange: string;
  freshness: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface DocumentDetail {
  kind: 'document';
  role: string;
  title: string;
  id: string;
  availability: string;
  sourceExperiment: string;
  updatedDate: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface ArtifactDetail {
  kind: 'artifact';
  role: string;
  title: string;
  id: string;
  artifactType: string;
  fileCount: number;
  files: string[];
  generatedDate: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface ExperimentDetail {
  kind: 'experiment';
  role: string;
  title: string;
  id: string;
  summary: string;
  status: string;
  date: string;
  stage: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface RelationshipDetailModel {
  kind: 'relationship';
  from: InOutEntity;
  to: InOutEntity;
  edgeType: string;
  explanation: string;
  basis: string;
  bothEndpointsVisible: boolean;
  scope: 'visible' | 'external' | 'unresolved';
  actions: InOutDetailAction[];
}

export type InOutDetail =
  | FindingDetail
  | QuestionDetail
  | DatasetDetail
  | DocumentDetail
  | ArtifactDetail
  | ExperimentDetail
  | RelationshipDetailModel;

// ── Map-level entity (lightweight, for cards) ──────────────────────────

export interface InOutEntity {
  id: string;
  kind: InOutEntityKind;
  title: string;
  status?: string;
  confidence?: string;
  href?: string;
  unresolved?: boolean;
}

// ── Inputs ──────────────────────────────────────────────────────────────

export type InOutInputRole = 'previous-finding' | 'previous-question' | 'source-data' | 'source-document';

export interface InOutInput {
  id: string;
  role: InOutInputRole;
  entity: InOutEntity;
  note?: string;
  group: 'data' | 'documents' | 'previous-findings' | 'previous-questions';
}

// ── Outputs ─────────────────────────────────────────────────────────────

export type InOutOutputRole = 'produced-finding' | 'produced-question' | 'updated-finding' | 'carried-forward' | 'artifact';

export type InOutOutputGroup = 'produced' | 'updated' | 'carried-forward' | 'open-questions' | 'artifacts';

export interface InOutOutput {
  id: string;
  role: InOutOutputRole;
  entity: InOutEntity;
  note?: string;
  group: InOutOutputGroup;
}

// ── Experiment ──────────────────────────────────────────────────────────

export type InOutExperimentStatus = 'completed' | 'in-progress' | 'planned' | 'exploration' | 'blocked';

export interface InOutExperiment {
  id: string;
  slug: string;
  title: string;
  status: InOutExperimentStatus;
  date: string;
  lastModified: string;
  description?: string;
  stage: string;
  entity: InOutEntity;
  meta: {
    findingsCount: number;
    questionsCount: number;
    figuresCount: number;
    producedCount: number;
    updatedCount: number;
    carriedForwardCount: number;
  };
}

// ── Relationships ───────────────────────────────────────────────────────

export type InOutRelationshipKind = 'input-to-experiment' | 'experiment-to-output' | 'cross-link' | 'external';
export type InOutRelationshipScope = 'visible' | 'external' | 'unresolved';

export interface InOutRelationship {
  id: string;
  kind: InOutRelationshipKind;
  scope: InOutRelationshipScope;
  from: InOutEntity;
  to: InOutEntity;
  edgeType: EdgeType | 'produces' | 'updates' | 'reuses' | 'cites';
  label: string;
  basis?: string;
  detail?: string;
  shownInMap: boolean;
}

export interface InOutViewModel {
  experiment: InOutExperiment | null;
  inputs: InOutInput[];
  outputs: InOutOutput[];
  relationships: InOutRelationship[];
  visibleRelationships: InOutRelationship[];
  additionalRelationships: InOutRelationship[];
}

// ── Summary counts ──────────────────────────────────────────────────────

export interface InOutSummary {
  inputs: number;
  produced: number;
  updated: number;
  carriedForward: number;
  artifacts: number;
  confirmedRelationships: number;
}

// ── Helpers ─────────────────────────────────────────────────────────────

export function formatRowCount(value: string | number | undefined): string {
  if (value == null) return '—';
  const str = String(value).trim();
  if (!str) return '—';
  const m = str.match(/^([\d,.]+)\s*(.*)$/);
  if (!m) return str;
  const num = m[1];
  const tail = m[2] ? ` ${m[2].replace(/\brows rows\b/g, 'rows')}` : '';
  return `${num}${tail}`.replace(/\s{2,}/g, ' ').trim();
}

export function pluralize(n: number, singular: string, plural: string): string {
  return `${n} ${n === 1 ? singular : plural}`;
}

export function formatShortId(id: string): string {
  return id.replace('experiments/', '');
}

function experimentStatus(e: Experiment): InOutExperimentStatus {
  if (e.outdated) return 'blocked';
  switch (e.reportStatus) {
    case 'report':
      return 'completed';
    case 'exploration-only':
      return 'exploration';
    case 'missing':
      return 'planned';
  }
}

function experimentStageLabel(e: Experiment): string {
  if (e.outdated) return 'Superseded data';
  switch (e.reportStatus) {
    case 'report':
      return 'REPORT.md published';
    case 'exploration-only':
      return 'README only';
    case 'missing':
      return 'No report yet';
  }
}

function findingAsEntity(f: Finding): InOutEntity {
  return {
    id: f.id,
    kind: 'finding',
    title: f.title,
    confidence: f.confidence,
    status: f.confidence === 'superseded' ? 'superseded' : undefined,
    href: `/findings?focus=${f.id}`,
  };
}

function questionAsEntity(q: OpenQuestion): InOutEntity {
  return {
    id: q.id,
    kind: 'question',
    title: q.title,
    status: q.status,
    href: `/findings?tab=questions&focus=${q.id}`,
  };
}

function experimentAsEntity(e: Experiment): InOutEntity {
  return {
    id: e.slug,
    kind: 'experiment',
    title: e.title,
    status: e.outdated ? 'outdated' : e.reportStatus,
    href: canonicalExperimentPath(e.slug),
  };
}

function buildExperimentVm(e: Experiment, producedCount: number, updatedCount: number, carriedForwardCount: number): InOutExperiment {
  return {
    id: e.slug,
    slug: e.slug,
    title: e.title,
    status: experimentStatus(e),
    date: e.date,
    lastModified: e.lastModified,
    description: e.conclusions[0],
    stage: experimentStageLabel(e),
    entity: experimentAsEntity(e),
    meta: {
      findingsCount: e.relatedFindings.length,
      questionsCount: e.relatedQuestions?.length ?? 0,
      figuresCount: e.figures.length,
      producedCount,
      updatedCount,
      carriedForwardCount,
    },
  };
}

function findingIsPredecessor(findingDate: string | undefined, experimentDate: string): boolean {
  if (!findingDate) return false;
  return findingDate < experimentDate;
}

// ── Relationship label mapping ──────────────────────────────────────────

const EDGE_TYPE_LABEL: Record<EdgeType, string> = {
  origin: 'originates',
  cite: 'cites',
  'report-use': 'uses',
  relates: 'relates to',
  'resolve-partial': 'partially resolves',
  'conflict-suspected': 'conflicts with',
  supersedes: 'supersedes',
  'relates-finding': 'relates to',
  addresses: 'addresses',
  strengthens: 'strengthens',
  resolves: 'resolves',
};

const EDGE_TYPE_VERB: Record<EdgeType, string> = {
  origin: 'originated from',
  cite: 'cites',
  'report-use': 'used in report',
  relates: 'relates to',
  'resolve-partial': 'partially resolves',
  'conflict-suspected': 'conflicts with',
  supersedes: 'superseded by',
  'relates-finding': 'relates to',
  addresses: 'addresses',
  strengthens: 'strengthens',
  resolves: 'resolves',
};

export function describeRelationshipSentence(
  fromEntity: InOutEntity,
  toEntity: InOutEntity,
  edgeType: EdgeType | 'produces' | 'updates' | 'reuses' | 'cites',
): string {
  if (edgeType === 'produces') return `${fromEntity.title} produces ${toEntity.title}`;
  if (edgeType === 'updates') return `${fromEntity.title} updates ${toEntity.title}`;
  if (edgeType === 'reuses') return `${fromEntity.title} is reused by ${toEntity.title}`;
  if (edgeType === 'cites') return `${fromEntity.title} cites ${toEntity.title}`;
  const verb = EDGE_TYPE_VERB[edgeType as EdgeType] ?? 'relates to';
  return `${fromEntity.title} ${verb} ${toEntity.title}`;
}

// ── Detail model builders ───────────────────────────────────────────────

export function buildFindingDetail(
  f: Finding,
  role: string,
  experiment: Experiment | null,
): FindingDetail {
  const relationship = experiment
    ? f.date < experiment.date
      ? `Predates ${experiment.title} — contributed as a previous finding.`
      : f.supersededBy
        ? `Updated by this experiment; superseded by ${f.supersededBy}.`
        : `Produced by ${experiment.title}.`
    : 'Relationship to experiment unavailable.';
  return {
    kind: 'finding',
    role,
    title: f.title,
    id: f.id,
    summary: f.summary,
    confidence: f.confidence,
    category: f.category,
    actionStatus: f.actionable ? 'Action required' : 'No action required',
    date: f.date,
    sourceExperiment: f.evidence,
    relationshipToCurrent: relationship,
    actions: [
      { label: 'Open finding', href: `/findings?focus=${f.id}`, icon: 'open' },
    ],
    unresolved: false,
  };
}

export function buildQuestionDetail(
  q: OpenQuestion,
  role: string,
  experiment: Experiment | null,
): QuestionDetail {
  const relationship = experiment
    ? `Raised before ${experiment.title}; referenced as context.`
    : 'Relationship to experiment unavailable.';
  return {
    kind: 'question',
    role,
    title: q.title,
    id: q.id,
    summary: q.detail.split('| Date:')[0].trim(),
    status: q.status,
    priority: q.priority,
    area: q.area,
    raisedDate: q.raisedDate,
    sourceExperiment: q.related.find((r) => r.startsWith('experiments/')) ?? '—',
    relationshipToCurrent: relationship,
    actions: [
      { label: 'Open question', href: `/findings?tab=questions&focus=${q.id}`, icon: 'open' },
    ],
    unresolved: false,
  };
}

export function buildDatasetDetail(
  experiment: Experiment,
  role: string,
): DatasetDetail {
  return {
    kind: 'dataset',
    role,
    title: 'Parquet inputs',
    id: `dataset:${formatShortId(experiment.slug)}`,
    rowCount: formatRowCount(experiment.freshness.rowCounts),
    dateRange: experiment.freshness.dateRange,
    freshness: experiment.freshness.parquetMtime,
    relationshipToCurrent: 'Source data consumed by this experiment.',
    actions: [],
    unresolved: false,
  };
}

export function buildDocumentDetail(
  experiment: Experiment,
  role: string,
): DocumentDetail {
  const isReport = experiment.reportStatus === 'report';
  return {
    kind: 'document',
    role,
    title: isReport ? 'REPORT.md' : 'README.md',
    id: `doc:${formatShortId(experiment.slug)}`,
    availability: isReport ? 'Report available' : experiment.reportStatus === 'exploration-only' ? 'README only' : 'No report yet',
    sourceExperiment: experiment.slug,
    updatedDate: experiment.lastModified,
    relationshipToCurrent: 'Source document for this experiment.',
    actions: [
      { label: 'Open document', href: canonicalExperimentPath(experiment.slug), icon: 'open' },
    ],
    unresolved: false,
  };
}

export function buildArtifactDetail(
  experiment: Experiment,
  role: string,
): ArtifactDetail {
  return {
    kind: 'artifact',
    role,
    title: pluralize(experiment.figures.length, 'figure', 'figures'),
    id: `artifacts:${formatShortId(experiment.slug)}`,
    artifactType: 'Figure',
    fileCount: experiment.figures.length,
    files: experiment.figures.map((f) => f.replace('outputs/figures/', '')),
    generatedDate: experiment.date,
    sourceExperiment: experiment.slug,
    relationshipToCurrent: 'Generated by this experiment.',
    actions: [
      { label: 'Open experiment', href: canonicalExperimentPath(experiment.slug), icon: 'preview' },
    ],
    unresolved: false,
  };
}

export function buildExperimentDetail(
  e: Experiment,
  role: string,
): ExperimentDetail {
  return {
    kind: 'experiment',
    role,
    title: e.title,
    id: e.slug,
    summary: e.conclusions[0] ?? '—',
    status: experimentStatus(e),
    date: e.date,
    stage: experimentStageLabel(e),
    relationshipToCurrent: 'This is the selected experiment.',
    actions: [
      { label: 'Open experiment report', href: canonicalExperimentPath(e.slug), icon: 'open' },
    ],
    unresolved: false,
  };
}

export function buildRelationshipDetailModel(
  r: InOutRelationship,
  experiment: Experiment | null,
): RelationshipDetailModel {
  const explanation = describeRelationshipSentence(r.from, r.to, r.edgeType);
  const bothVisible = r.scope === 'visible';
  return {
    kind: 'relationship',
    from: r.from,
    to: r.to,
    edgeType: r.label,
    explanation,
    basis: r.basis ?? '—',
    bothEndpointsVisible: bothVisible,
    scope: r.scope,
    actions: experiment
      ? [{ label: 'Open experiment report', href: canonicalExperimentPath(experiment.slug), icon: 'open' }]
      : [],
  };
}

// ── Adapter ─────────────────────────────────────────────────────────────

export interface BuildInOutOptions {
  experiments: Experiment[];
  findings: Finding[];
  openQuestions: OpenQuestion[];
  edges: Edge[];
  focusSlug?: string;
}

export function buildInOutViewModel(opts: BuildInOutOptions): InOutViewModel {
  const { experiments, findings, openQuestions, edges, focusSlug } = opts;

  const sorted = [...experiments].sort((a, b) => b.date.localeCompare(a.date));
  const experiment = focusSlug
    ? experiments.find((e) => e.slug === focusSlug || e.slug.endsWith(focusSlug))
    : sorted[0];

  if (!experiment) {
    return emptyViewModel();
  }

  const expEntity = experimentAsEntity(experiment);
  const findingMap = new Map(findings.map((f) => [f.id, f] as const));
  const questionMap = new Map(openQuestions.map((q) => [q.id, q] as const));

  // ── Inputs ────────────────────────────────────────────────────────────
  const inputs: InOutInput[] = [];
  const seenInput = new Set<string>();

  for (const fid of experiment.relatedFindings) {
    const f = findingMap.get(fid);
    if (!f) continue;
    if (!findingIsPredecessor(f.date, experiment.date)) continue;
    if (seenInput.has(fid)) continue;
    seenInput.add(fid);
    inputs.push({
      id: `input:finding:${fid}`,
      role: 'previous-finding',
      entity: findingAsEntity(f),
      group: 'previous-findings',
      note: f.confidence === 'superseded' ? 'Superseded claim' : undefined,
    });
  }
  for (const qid of experiment.relatedQuestions ?? []) {
    const q = questionMap.get(qid);
    if (!q) continue;
    if (seenInput.has(qid)) continue;
    seenInput.add(qid);
    inputs.push({
      id: `input:question:${qid}`,
      role: 'previous-question',
      entity: questionAsEntity(q),
      group: 'previous-questions',
      note: q.status === 'resolved' ? 'Resolved' : undefined,
    });
  }

  inputs.push({
    id: `input:dataset:${experiment.slug}`,
    role: 'source-data',
    entity: {
      id: `dataset:${experiment.slug}`,
      kind: 'dataset',
      title: 'Parquet inputs',
      status: `${formatRowCount(experiment.freshness.rowCounts)} · ${experiment.freshness.dateRange}`,
    },
    group: 'data',
    note: experiment.freshness.parquetMtime,
  });
  inputs.push({
    id: `input:document:${experiment.slug}`,
    role: 'source-document',
    entity: {
      id: `doc:${experiment.slug}`,
      kind: 'document',
      title: experiment.reportStatus === 'report' ? 'REPORT.md' : 'README.md',
      status: experiment.reportStatus === 'report' ? 'Report available' : experiment.reportStatus,
    },
    group: 'documents',
    note: experiment.slug,
  });

  // ── Outputs ───────────────────────────────────────────────────────────
  const outputs: InOutOutput[] = [];
  const seenOutput = new Set<string>();
  let producedCount = 0;
  let updatedCount = 0;
  let carriedForwardCount = 0;

  for (const fid of experiment.relatedFindings) {
    const f = findingMap.get(fid);
    if (!f) continue;
    if (seenOutput.has(fid)) continue;
    seenOutput.add(fid);

    const predates = findingIsPredecessor(f.date, experiment.date);
    if (predates) {
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'carried-forward',
        entity: findingAsEntity(f),
        group: 'carried-forward',
        note: 'Reference from a prior experiment',
      });
      carriedForwardCount++;
    } else if (f.supersededBy) {
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'updated-finding',
        entity: findingAsEntity(f),
        group: 'updated',
        note: `Updated by ${f.supersededBy}`,
      });
      updatedCount++;
    } else {
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'produced-finding',
        entity: findingAsEntity(f),
        group: 'produced',
      });
      producedCount++;
    }
  }
  for (const qid of experiment.relatedQuestions ?? []) {
    const q = questionMap.get(qid);
    if (!q) continue;
    if (seenOutput.has(qid)) continue;
    seenOutput.add(qid);
    outputs.push({
      id: `output:question:${qid}`,
      role: 'produced-question',
      entity: questionAsEntity(q),
      group: 'open-questions',
    });
  }
  if (experiment.figures.length > 0) {
    outputs.push({
      id: `output:artifacts:${experiment.slug}`,
      role: 'artifact',
      entity: {
        id: `artifacts:${experiment.slug}`,
        kind: 'artifact',
        title: pluralize(experiment.figures.length, 'figure', 'figures'),
        href: canonicalExperimentPath(experiment.slug),
      },
      group: 'artifacts',
    });
  }

  // ── Visible relationships ─────────────────────────────────────────────
  const visibleRelationships: InOutRelationship[] = [];
  for (const input of inputs) {
    if (input.role === 'previous-finding' || input.role === 'previous-question') {
      visibleRelationships.push({
        id: `rel:visible:in:${input.id}:${experiment.slug}`,
        kind: 'input-to-experiment',
        scope: 'visible',
        from: input.entity,
        to: expEntity,
        edgeType: 'origin',
        label: 'informs',
        basis: 'relatedFindings / relatedQuestions',
        detail: `${input.entity.id} predates the experiment`,
        shownInMap: true,
      });
    }
  }
  for (const output of outputs) {
    if (
      output.role === 'produced-finding' ||
      output.role === 'produced-question' ||
      output.role === 'updated-finding' ||
      output.role === 'carried-forward'
    ) {
      visibleRelationships.push({
        id: `rel:visible:out:${experiment.slug}:${output.id}`,
        kind: 'experiment-to-output',
        scope: 'visible',
        from: expEntity,
        to: output.entity,
        edgeType: output.role === 'updated-finding' ? 'updates' : output.role === 'carried-forward' ? 'reuses' : 'produces',
        label: output.role === 'updated-finding' ? 'updates' : output.role === 'carried-forward' ? 'reuses' : 'produced',
        basis: 'relatedFindings / relatedQuestions',
        detail: `${output.entity.id} is registered against this experiment`,
        shownInMap: true,
      });
    }
  }

  // ── Additional relationships ──────────────────────────────────────────
  const additionalRelationships: InOutRelationship[] = [];
  const inputEntityIds = new Set(inputs.map((i) => i.entity.id));
  const outputEntityIds = new Set(outputs.map((o) => o.entity.id));

  for (const edge of edges) {
    const fromIn = inputEntityIds.has(edge.src) || outputEntityIds.has(edge.src) || edge.src === experiment.slug;
    const toIn = inputEntityIds.has(edge.dst) || outputEntityIds.has(edge.dst) || edge.dst === experiment.slug;
    if (!fromIn || !toIn) continue;

    if (edge.src === experiment.slug || edge.dst === experiment.slug) {
      if (visibleRelationships.some((r) => r.from.id === edge.src && r.to.id === edge.dst)) continue;
      if (visibleRelationships.some((r) => r.from.id === edge.dst && r.to.id === edge.src)) continue;
    }

    const fromEntity = resolveEntityStrict(edge.src, findings, openQuestions, experiments);
    const toEntity = resolveEntityStrict(edge.dst, findings, openQuestions, experiments);

    const isVisible =
      fromEntity.kind !== 'unknown' &&
      toEntity.kind !== 'unknown' &&
      (inputEntityIds.has(fromEntity.id) || outputEntityIds.has(fromEntity.id) || fromEntity.id === experiment.slug) &&
      (inputEntityIds.has(toEntity.id) || outputEntityIds.has(toEntity.id) || toEntity.id === experiment.slug);

    const relationship: InOutRelationship = {
      id: `rel:extra:${edge.src}:${edge.edgeType}:${edge.dst}`,
      kind: isVisible ? 'cross-link' : 'external',
      scope: fromEntity.kind === 'unknown' || toEntity.kind === 'unknown' ? 'unresolved' : isVisible ? 'visible' : 'external',
      from: fromEntity,
      to: toEntity,
      edgeType: edge.edgeType,
      label: EDGE_TYPE_LABEL[edge.edgeType] ?? 'relates to',
      basis: edge.basis,
      detail: edge.detail,
      shownInMap: isVisible,
    };
    additionalRelationships.push(relationship);
  }

  const all = [...visibleRelationships, ...additionalRelationships];
  return {
    experiment: buildExperimentVm(experiment, producedCount, updatedCount, carriedForwardCount),
    inputs,
    outputs,
    relationships: all,
    visibleRelationships,
    additionalRelationships,
  };
}

function emptyViewModel(): InOutViewModel {
  return {
    experiment: null,
    inputs: [],
    outputs: [],
    relationships: [],
    visibleRelationships: [],
    additionalRelationships: [],
  };
}

export function getSummary(vm: InOutViewModel): InOutSummary {
  return {
    inputs: vm.inputs.length,
    produced: vm.outputs.filter((o) => o.group === 'produced').length,
    updated: vm.outputs.filter((o) => o.group === 'updated').length,
    carriedForward: vm.outputs.filter((o) => o.group === 'carried-forward').length,
    artifacts: vm.outputs.filter((o) => o.group === 'artifacts').length,
    confirmedRelationships: vm.visibleRelationships.length,
  };
}

// ── Entity resolver (strict) ────────────────────────────────────────────

export function resolveEntityStrict(
  id: string,
  findings: Finding[],
  openQuestions: OpenQuestion[],
  experiments: Experiment[],
): InOutEntity {
  if (id.startsWith('F-')) {
    const f = findings.find((x) => x.id === id);
    return f ? findingAsEntity(f) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('Q-')) {
    const q = openQuestions.find((x) => x.id === id);
    return q ? questionAsEntity(q) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('experiments/')) {
    const e = experiments.find((x) => x.slug === id);
    return e ? experimentAsEntity(e) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('input:finding:')) {
    const fid = id.replace('input:finding:', '');
    const f = findings.find((x) => x.id === fid);
    return f ? findingAsEntity(f) : { id: fid, kind: 'unknown', title: fid, unresolved: true };
  }
  if (id.startsWith('input:question:')) {
    const qid = id.replace('input:question:', '');
    const q = openQuestions.find((x) => x.id === qid);
    return q ? questionAsEntity(q) : { id: qid, kind: 'unknown', title: qid, unresolved: true };
  }
  if (id.startsWith('output:finding:')) {
    const fid = id.replace('output:finding:', '');
    const f = findings.find((x) => x.id === fid);
    return f ? findingAsEntity(f) : { id: fid, kind: 'unknown', title: fid, unresolved: true };
  }
  if (id.startsWith('output:question:')) {
    const qid = id.replace('output:question:', '');
    const q = openQuestions.find((x) => x.id === qid);
    return q ? questionAsEntity(q) : { id: qid, kind: 'unknown', title: qid, unresolved: true };
  }
  return { id, kind: 'unknown', title: id, unresolved: true };
}
