// In/Out view model — provenance-aware entity classification.
//
// Design rules:
// 1. An entity that predates the experiment is an input.
// 2. An entity whose state was changed by the experiment is shown on
//    both sides — as an input (previous state) and as an outcome
//    (transition). The transition role makes the change explicit.
// 3. An entity newly created by the experiment is only an outcome.
// 4. REPORT.md generated by the experiment is an outcome, not an input.
// 5. Confidence is never labeled as "status".
// 6. Raw internal routes are never rendered as primary content.
// 7. Summary counts match the rendered outcome groups.

import type { Edge, EdgeType, Experiment, Finding, OpenQuestion } from './types';
import { canonicalExperimentPath } from './routes';

// ── Entity kinds ────────────────────────────────────────────────────────

export type InOutEntityKind = 'finding' | 'question' | 'experiment' | 'dataset' | 'document' | 'artifact' | 'report' | 'unknown';

// ── Detail action ───────────────────────────────────────────────────────

export interface InOutDetailAction {
  label: string;
  href: string;
  icon?: 'open' | 'preview' | 'inspect';
}

// ── Entity-specific detail view models ──────────────────────────────────

export interface FindingDetail {
  kind: 'finding';
  role: string;
  title: string;
  id: string;
  summary: string;
  confidence: string;
  category: string;
  actionStatus: string;
  date: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  previousState?: string;
  resultingState?: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface QuestionDetail {
  kind: 'question';
  role: string;
  title: string;
  id: string;
  summary: string;
  status: string;
  priority: string;
  area: string;
  raisedDate: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  previousState?: string;
  resultingState?: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface DatasetDetail {
  kind: 'dataset';
  role: string;
  title: string;
  id: string;
  rowCount: string;
  dateRange: string;
  freshness: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface DocumentDetail {
  kind: 'document';
  role: string;
  title: string;
  id: string;
  availability: string;
  sourceExperiment: string;
  updatedDate: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface ArtifactDetail {
  kind: 'artifact';
  role: string;
  title: string;
  id: string;
  artifactType: string;
  fileCount: number;
  files: string[];
  generatedDate: string;
  sourceExperiment: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface ExperimentDetail {
  kind: 'experiment';
  role: string;
  title: string;
  id: string;
  summary: string;
  status: string;
  date: string;
  stage: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface ReportDetail {
  kind: 'report';
  role: string;
  title: string;
  id: string;
  availability: string;
  sourceExperiment: string;
  generatedDate: string;
  relationshipToCurrent: string;
  actions: InOutDetailAction[];
  unresolved: boolean;
}

export interface RelationshipDetailModel {
  kind: 'relationship';
  from: InOutEntity;
  to: InOutEntity;
  edgeType: string;
  explanation: string;
  basis: string;
  bothEndpointsVisible: boolean;
  scope: 'visible' | 'external' | 'unresolved';
  actions: InOutDetailAction[];
}

export type InOutDetail =
  | FindingDetail
  | QuestionDetail
  | DatasetDetail
  | DocumentDetail
  | ArtifactDetail
  | ExperimentDetail
  | ReportDetail
  | RelationshipDetailModel;

// ── Map-level entity ────────────────────────────────────────────────────

export interface InOutEntity {
  id: string;
  kind: InOutEntityKind;
  title: string;
  status?: string;
  confidence?: string;
  href?: string;
  unresolved?: boolean;
}

// ── Inputs ──────────────────────────────────────────────────────────────

export type InOutInputRole = 'previous-finding' | 'previous-question' | 'source-data' | 'source-document';

export interface InOutInput {
  id: string;
  role: InOutInputRole;
  entity: InOutEntity;
  note?: string;
  /** Human-readable display label for the card (not a synthetic id). */
  displayId?: string;
  group: 'data' | 'documents' | 'previous-findings' | 'previous-questions';
}

// ── Outputs — provenance-aware roles ────────────────────────────────────

export type InOutOutputRole =
  | 'produced-finding'
  | 'produced-question'
  | 'updated-finding'
  | 'resolved-question'
  | 'partially-resolved-question'
  | 'updated-question'
  | 'carried-forward'
  | 'artifact'
  | 'generated-report';

export type InOutOutputGroup =
  | 'new-findings'
  | 'new-questions'
  | 'updated-findings'
  | 'resolved-questions'
  | 'carried-forward'
  | 'artifacts'
  | 'generated-report';

export interface InOutOutput {
  id: string;
  role: InOutOutputRole;
  entity: InOutEntity;
  note?: string;
  /** Human-readable display label for the card. */
  displayId?: string;
  /** Previous state for transition display. */
  previousState?: string;
  /** Resulting state for transition display. */
  resultingState?: string;
  group: InOutOutputGroup;
}

// ── Experiment ──────────────────────────────────────────────────────────

export type InOutExperimentStatus = 'completed' | 'in-progress' | 'planned' | 'exploration' | 'blocked';

export interface InOutExperiment {
  id: string;
  slug: string;
  title: string;
  status: InOutExperimentStatus;
  date: string;
  lastModified: string;
  description?: string;
  stage: string;
  entity: InOutEntity;
}

// ── Relationships ───────────────────────────────────────────────────────

export type InOutRelationshipKind = 'input-to-experiment' | 'experiment-to-output' | 'cross-link' | 'external' | 'transition';
export type InOutRelationshipScope = 'visible' | 'external' | 'unresolved';

export interface InOutRelationship {
  id: string;
  kind: InOutRelationshipKind;
  scope: InOutRelationshipScope;
  from: InOutEntity;
  to: InOutEntity;
  edgeType: EdgeType | 'produces' | 'updates' | 'reuses' | 'cites' | 'resolves' | 'partially-resolves' | 'transitions';
  label: string;
  basis?: string;
  detail?: string;
  shownInMap: boolean;
}

export interface InOutViewModel {
  experiment: InOutExperiment | null;
  inputs: InOutInput[];
  outputs: InOutOutput[];
  relationships: InOutRelationship[];
  visibleRelationships: InOutRelationship[];
  additionalRelationships: InOutRelationship[];
}

// ── Summary counts — match rendered groups ──────────────────────────────

export interface InOutSummary {
  inputs: number;
  newFindings: number;
  newQuestions: number;
  updatedFindings: number;
  resolvedQuestions: number;
  carriedForward: number;
  artifacts: number;
  generatedReport: boolean;
  connections: number;
}

// ── Helpers ─────────────────────────────────────────────────────────────

export function formatRowCount(value: string | number | undefined): string {
  if (value == null) return '—';
  const str = String(value).trim();
  if (!str) return '—';
  const m = str.match(/^([\d,.]+)\s*(.*)$/);
  if (!m) return str;
  const num = m[1];
  const tail = m[2] ? ` ${m[2].replace(/\brows rows\b/g, 'rows')}` : '';
  return `${num}${tail}`.replace(/\s{2,}/g, ' ').trim();
}

export function pluralize(n: number, singular: string, plural: string): string {
  return `${n} ${n === 1 ? singular : plural}`;
}

export function formatShortId(id: string): string {
  return id.replace('experiments/', '');
}

function experimentStatus(e: Experiment): InOutExperimentStatus {
  if (e.outdated) return 'blocked';
  switch (e.reportStatus) {
    case 'report': return 'completed';
    case 'exploration-only': return 'exploration';
    case 'missing': return 'planned';
  }
}

function experimentStageLabel(e: Experiment): string {
  if (e.outdated) return 'Superseded data';
  switch (e.reportStatus) {
    case 'report': return 'REPORT.md published';
    case 'exploration-only': return 'README only';
    case 'missing': return 'No report yet';
  }
}

function findingAsEntity(f: Finding): InOutEntity {
  return {
    id: f.id,
    kind: 'finding',
    title: f.title,
    confidence: f.confidence,
    status: f.confidence === 'superseded' ? 'superseded' : undefined,
    href: `/findings?focus=${f.id}`,
  };
}

function questionAsEntity(q: OpenQuestion): InOutEntity {
  return {
    id: q.id,
    kind: 'question',
    title: q.title,
    status: q.status,
    href: `/findings?tab=questions&focus=${q.id}`,
  };
}

function experimentAsEntity(e: Experiment): InOutEntity {
  return {
    id: e.slug,
    kind: 'experiment',
    title: e.title,
    status: e.outdated ? 'outdated' : e.reportStatus,
    href: canonicalExperimentPath(e.slug),
  };
}

function buildExperimentVm(e: Experiment): InOutExperiment {
  return {
    id: e.slug,
    slug: e.slug,
    title: e.title,
    status: experimentStatus(e),
    date: e.date,
    lastModified: e.lastModified,
    description: e.conclusions[0],
    stage: experimentStageLabel(e),
    entity: experimentAsEntity(e),
  };
}

function findingIsPredecessor(findingDate: string | undefined, experimentDate: string): boolean {
  if (!findingDate) return false;
  return findingDate < experimentDate;
}

function questionIsPredecessor(raisedDate: string, experimentDate: string): boolean {
  return raisedDate < experimentDate;
}

// ── Relationship label mapping ──────────────────────────────────────────

const EDGE_TYPE_LABEL: Record<EdgeType, string> = {
  origin: 'originates',
  cite: 'cites',
  'report-use': 'uses',
  relates: 'relates to',
  'resolve-partial': 'partially resolves',
  'conflict-suspected': 'conflicts with',
  supersedes: 'supersedes',
  'relates-finding': 'relates to',
  addresses: 'addresses',
  strengthens: 'strengthens',
  resolves: 'resolves',
};

const EDGE_TYPE_VERB: Record<EdgeType, string> = {
  origin: 'originated from',
  cite: 'cites',
  'report-use': 'used in report',
  relates: 'relates to',
  'resolve-partial': 'partially resolves',
  'conflict-suspected': 'conflicts with',
  supersedes: 'superseded by',
  'relates-finding': 'relates to',
  addresses: 'addresses',
  strengthens: 'strengthens',
  resolves: 'resolves',
};

export function describeRelationshipSentence(
  fromEntity: InOutEntity,
  toEntity: InOutEntity,
  edgeType: EdgeType | 'produces' | 'updates' | 'reuses' | 'cites' | 'resolves' | 'partially-resolves' | 'transitions',
): string {
  if (edgeType === 'produces') return `${fromEntity.title} produces ${toEntity.title}`;
  if (edgeType === 'updates') return `${fromEntity.title} updates ${toEntity.title}`;
  if (edgeType === 'reuses') return `${fromEntity.title} reuses ${toEntity.title}`;
  if (edgeType === 'cites') return `${fromEntity.title} cites ${toEntity.title}`;
  if (edgeType === 'resolves') return `${fromEntity.title} resolves ${toEntity.title}`;
  if (edgeType === 'partially-resolves') return `${fromEntity.title} partially resolves ${toEntity.title}`;
  if (edgeType === 'transitions') return `${fromEntity.title} transitions to ${toEntity.title}`;
  const verb = EDGE_TYPE_VERB[edgeType as EdgeType] ?? 'relates to';
  return `${fromEntity.title} ${verb} ${toEntity.title}`;
}

// ── Detail model builders ───────────────────────────────────────────────

export function buildFindingDetail(f: Finding, role: string, experiment: Experiment | null): FindingDetail {
  const relationship = experiment
    ? f.date < experiment.date
      ? f.supersededBy
        ? `Updated by this experiment; superseded by ${f.supersededBy}.`
        : `Carried forward as a reference from before ${experiment.title}.`
      : `Produced by ${experiment.title}.`
    : 'Relationship to experiment unavailable.';
  return {
    kind: 'finding', role, title: f.title, id: f.id, summary: f.summary,
    confidence: f.confidence, category: f.category,
    actionStatus: f.actionable ? 'Action required' : 'No action required',
    date: f.date, sourceExperiment: f.evidence,
    relationshipToCurrent: relationship,
    actions: [{ label: 'Open finding', href: `/findings?focus=${f.id}`, icon: 'open' }],
    unresolved: false,
  };
}

export function buildQuestionDetail(q: OpenQuestion, role: string, experiment: Experiment | null, previousState?: string): QuestionDetail {
  const resultingState = q.status;
  const relationship = experiment
    ? questionIsPredecessor(q.raisedDate, experiment.date)
      ? role === 'resolved-question'
        ? `Resolved by ${experiment.title}.`
        : role === 'partially-resolved-question'
          ? `Partially resolved by ${experiment.title}.`
          : role === 'updated-question'
            ? `Advanced by ${experiment.title}.`
            : `Raised before ${experiment.title}; referenced as context.`
      : `Newly created by ${experiment.title}.`
    : 'Relationship to experiment unavailable.';
  return {
    kind: 'question', role, title: q.title, id: q.id,
    summary: q.detail.split('| Date:')[0].trim(),
    status: q.status, priority: q.priority, area: q.area, raisedDate: q.raisedDate,
    sourceExperiment: q.related.find((r) => r.startsWith('experiments/')) ?? '—',
    relationshipToCurrent: relationship,
    previousState, resultingState,
    actions: [{ label: 'Open question', href: `/findings?tab=questions&focus=${q.id}`, icon: 'open' }],
    unresolved: false,
  };
}

export function buildDatasetDetail(experiment: Experiment, role: string): DatasetDetail {
  return {
    kind: 'dataset', role, title: 'Parquet inputs',
    id: formatShortId(experiment.slug),
    rowCount: formatRowCount(experiment.freshness.rowCounts),
    dateRange: experiment.freshness.dateRange,
    freshness: experiment.freshness.parquetMtime,
    relationshipToCurrent: 'Source data consumed by this experiment.',
    actions: [], unresolved: false,
  };
}

export function buildDocumentDetail(experiment: Experiment, role: string): DocumentDetail {
  return {
    kind: 'document', role, title: 'README.md',
    id: formatShortId(experiment.slug),
    availability: 'README available',
    sourceExperiment: experiment.slug,
    updatedDate: experiment.lastModified,
    relationshipToCurrent: 'Source document for this experiment.',
    actions: [{ label: 'Open document', href: canonicalExperimentPath(experiment.slug), icon: 'open' }],
    unresolved: false,
  };
}

export function buildReportDetail(experiment: Experiment, role: string): ReportDetail {
  return {
    kind: 'report', role, title: 'REPORT.md',
    id: formatShortId(experiment.slug),
    availability: 'Report available',
    sourceExperiment: experiment.slug,
    generatedDate: experiment.date,
    relationshipToCurrent: 'Generated by this experiment.',
    actions: [{ label: 'Open report', href: canonicalExperimentPath(experiment.slug), icon: 'open' }],
    unresolved: false,
  };
}

export function buildArtifactDetail(experiment: Experiment, role: string): ArtifactDetail {
  return {
    kind: 'artifact', role,
    title: pluralize(experiment.figures.length, 'figure', 'figures'),
    id: formatShortId(experiment.slug),
    artifactType: 'Figure',
    fileCount: experiment.figures.length,
    files: experiment.figures.map((f) => f.replace('outputs/figures/', '')),
    generatedDate: experiment.date,
    sourceExperiment: experiment.slug,
    relationshipToCurrent: 'Generated by this experiment.',
    actions: [{ label: 'Open experiment', href: canonicalExperimentPath(experiment.slug), icon: 'preview' }],
    unresolved: false,
  };
}

export function buildExperimentDetail(e: Experiment, role: string): ExperimentDetail {
  return {
    kind: 'experiment', role, title: e.title, id: e.slug,
    summary: e.conclusions[0] ?? '—',
    status: experimentStatus(e), date: e.date, stage: experimentStageLabel(e),
    relationshipToCurrent: 'This is the selected experiment.',
    actions: [{ label: 'Open experiment report', href: canonicalExperimentPath(e.slug), icon: 'open' }],
    unresolved: false,
  };
}

export function buildRelationshipDetailModel(r: InOutRelationship, experiment: Experiment | null): RelationshipDetailModel {
  return {
    kind: 'relationship', from: r.from, to: r.to,
    edgeType: r.label,
    explanation: describeRelationshipSentence(r.from, r.to, r.edgeType),
    basis: r.basis ?? '—',
    bothEndpointsVisible: r.scope === 'visible',
    scope: r.scope,
    actions: experiment ? [{ label: 'Open experiment report', href: canonicalExperimentPath(experiment.slug), icon: 'open' }] : [],
  };
}

// ── Adapter ─────────────────────────────────────────────────────────────

export interface BuildInOutOptions {
  experiments: Experiment[];
  findings: Finding[];
  openQuestions: OpenQuestion[];
  edges: Edge[];
  focusSlug?: string;
}

export function buildInOutViewModel(opts: BuildInOutOptions): InOutViewModel {
  const { experiments, findings, openQuestions, edges, focusSlug } = opts;

  const sorted = [...experiments].sort((a, b) => b.date.localeCompare(a.date));
  const experiment = focusSlug
    ? experiments.find((e) => e.slug === focusSlug || e.slug.endsWith(focusSlug))
    : sorted[0];

  if (!experiment) return emptyViewModel();

  const expEntity = experimentAsEntity(experiment);
  const findingMap = new Map(findings.map((f) => [f.id, f] as const));
  const questionMap = new Map(openQuestions.map((q) => [q.id, q] as const));

  // Build a set of question IDs that this experiment resolves or partially resolves,
  // based on knowledge-graph edges where a finding produced by this experiment
  // has a 'resolves' or 'resolve-partial' edge to the question.
  const resolvedByExperiment = new Map<string, 'resolves' | 'resolve-partial'>();
  for (const edge of edges) {
    if (edge.edgeType === 'resolves' || edge.edgeType === 'resolve-partial') {
      // Check if the source finding is in this experiment's relatedFindings
      if (experiment.relatedFindings.includes(edge.src) || edge.src === experiment.slug) {
        resolvedByExperiment.set(edge.dst, edge.edgeType === 'resolves' ? 'resolves' : 'resolve-partial');
      }
    }
  }

  // ── Inputs ────────────────────────────────────────────────────────────
  const inputs: InOutInput[] = [];
  const seenInputEntityIds = new Set<string>();

  // Previous findings (predate the experiment)
  for (const fid of experiment.relatedFindings) {
    const f = findingMap.get(fid);
    if (!f) continue;
    if (!findingIsPredecessor(f.date, experiment.date)) continue;
    if (seenInputEntityIds.has(fid)) continue;
    seenInputEntityIds.add(fid);
    inputs.push({
      id: `input:finding:${fid}`,
      role: 'previous-finding',
      entity: findingAsEntity(f),
      displayId: fid,
      group: 'previous-findings',
      note: f.confidence === 'superseded' ? 'Superseded' : undefined,
    });
  }

  // Previous questions (raised before the experiment)
  for (const qid of experiment.relatedQuestions ?? []) {
    const q = questionMap.get(qid);
    if (!q) continue;
    if (!questionIsPredecessor(q.raisedDate, experiment.date)) continue;
    if (seenInputEntityIds.has(qid)) continue;
    seenInputEntityIds.add(qid);
    inputs.push({
      id: `input:question:${qid}`,
      role: 'previous-question',
      entity: questionAsEntity(q),
      displayId: qid,
      group: 'previous-questions',
      note: q.status,
    });
  }

  // Source data (parquet inputs)
  inputs.push({
    id: `input:dataset:${experiment.slug}`,
    role: 'source-data',
    entity: {
      id: `dataset:${formatShortId(experiment.slug)}`,
      kind: 'dataset',
      title: 'Parquet inputs',
      status: `${formatRowCount(experiment.freshness.rowCounts)} · ${experiment.freshness.dateRange}`,
    },
    displayId: formatShortId(experiment.slug),
    group: 'data',
    note: experiment.freshness.parquetMtime,
  });

  // Source document — README.md is the input, NOT REPORT.md
  inputs.push({
    id: `input:document:${experiment.slug}`,
    role: 'source-document',
    entity: {
      id: `doc:${formatShortId(experiment.slug)}`,
      kind: 'document',
      title: 'README.md',
      status: 'Input document',
    },
    displayId: formatShortId(experiment.slug),
    group: 'documents',
  });

  // ── Outputs (Outcomes) ────────────────────────────────────────────────
  const outputs: InOutOutput[] = [];
  const seenOutputEntityIds = new Set<string>();

  // Findings
  for (const fid of experiment.relatedFindings) {
    const f = findingMap.get(fid);
    if (!f) continue;
    if (seenOutputEntityIds.has(fid)) continue;
    seenOutputEntityIds.add(fid);

    const predates = findingIsPredecessor(f.date, experiment.date);
    if (predates) {
      // Carried forward — existed before, unchanged
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'carried-forward',
        entity: findingAsEntity(f),
        displayId: fid,
        group: 'carried-forward',
        note: 'Reference from a prior experiment',
      });
    } else if (f.supersededBy) {
      // Updated — produced by this experiment but later superseded
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'updated-finding',
        entity: findingAsEntity(f),
        displayId: fid,
        group: 'updated-findings',
        note: `Superseded by ${f.supersededBy}`,
      });
    } else {
      // Newly produced
      outputs.push({
        id: `output:finding:${fid}`,
        role: 'produced-finding',
        entity: findingAsEntity(f),
        displayId: fid,
        group: 'new-findings',
      });
    }
  }

  // Questions — distinguish transitions from new creations
  for (const qid of experiment.relatedQuestions ?? []) {
    const q = questionMap.get(qid);
    if (!q) continue;
    if (seenOutputEntityIds.has(qid)) continue;
    seenOutputEntityIds.add(qid);

    const predates = questionIsPredecessor(q.raisedDate, experiment.date);
    if (!predates) {
      // Newly created by this experiment
      outputs.push({
        id: `output:question:${qid}`,
        role: 'produced-question',
        entity: questionAsEntity(q),
        displayId: qid,
        group: 'new-questions',
      });
    } else {
      // Transition — existed before, state changed by this experiment
      const resolveType = resolvedByExperiment.get(qid);
      if (resolveType === 'resolves' || q.status === 'resolved') {
        outputs.push({
          id: `output:question:${qid}`,
          role: 'resolved-question',
          entity: questionAsEntity(q),
          displayId: qid,
          group: 'resolved-questions',
          previousState: 'Open',
          resultingState: 'Resolved',
          note: 'Open → Resolved',
        });
      } else if (resolveType === 'resolve-partial' || q.status === 'partial-progress') {
        outputs.push({
          id: `output:question:${qid}`,
          role: 'partially-resolved-question',
          entity: questionAsEntity(q),
          displayId: qid,
          group: 'resolved-questions',
          previousState: 'Open',
          resultingState: 'Partial progress',
          note: 'Open → Partial progress',
        });
      } else if (q.status === 'in-progress') {
        outputs.push({
          id: `output:question:${qid}`,
          role: 'updated-question',
          entity: questionAsEntity(q),
          displayId: qid,
          group: 'resolved-questions',
          previousState: 'Open',
          resultingState: 'In progress',
          note: 'Open → In progress',
        });
      } else {
        // Carried forward unchanged
        outputs.push({
          id: `output:question:${qid}`,
          role: 'carried-forward',
          entity: questionAsEntity(q),
          displayId: qid,
          group: 'carried-forward',
          note: 'Unchanged reference',
        });
      }
    }
  }

  // Generated report — REPORT.md is an output, NOT an input
  if (experiment.reportStatus === 'report') {
    outputs.push({
      id: `output:report:${experiment.slug}`,
      role: 'generated-report',
      entity: {
        id: `report:${formatShortId(experiment.slug)}`,
        kind: 'report',
        title: 'REPORT.md',
        href: canonicalExperimentPath(experiment.slug),
      },
      displayId: formatShortId(experiment.slug),
      group: 'generated-report',
      note: 'Generated by this experiment',
    });
  }

  // Generated artifacts (figures)
  if (experiment.figures.length > 0) {
    outputs.push({
      id: `output:artifacts:${experiment.slug}`,
      role: 'artifact',
      entity: {
        id: `artifacts:${formatShortId(experiment.slug)}`,
        kind: 'artifact',
        title: pluralize(experiment.figures.length, 'figure', 'figures'),
        href: canonicalExperimentPath(experiment.slug),
      },
      displayId: formatShortId(experiment.slug),
      group: 'artifacts',
    });
  }

  // ── Visible relationships ─────────────────────────────────────────────
  const visibleRelationships: InOutRelationship[] = [];

  // Input → Experiment
  for (const input of inputs) {
    if (input.role === 'previous-finding' || input.role === 'previous-question') {
      visibleRelationships.push({
        id: `rel:visible:in:${input.id}:${experiment.slug}`,
        kind: 'input-to-experiment',
        scope: 'visible',
        from: input.entity,
        to: expEntity,
        edgeType: 'origin',
        label: 'informs',
        basis: 'relatedFindings / relatedQuestions',
        detail: `${input.entity.id} predates the experiment`,
        shownInMap: true,
      });
    }
  }

  // Experiment → Output
  for (const output of outputs) {
    const isTransition = output.role === 'resolved-question' || output.role === 'partially-resolved-question' || output.role === 'updated-question';
    const isProduced = output.role === 'produced-finding' || output.role === 'produced-question';
    const isUpdated = output.role === 'updated-finding';
    const isCarried = output.role === 'carried-forward';
    const isArtifact = output.role === 'artifact' || output.role === 'generated-report';

    if (isProduced || isUpdated || isCarried || isArtifact || isTransition) {
      let edgeType: InOutRelationship['edgeType'] = 'produces';
      let label = 'produces';
      if (isUpdated) { edgeType = 'updates'; label = 'updates'; }
      else if (isCarried) { edgeType = 'reuses'; label = 'reuses'; }
      else if (isTransition) {
        edgeType = output.role === 'resolved-question' ? 'resolves' : output.role === 'partially-resolved-question' ? 'partially-resolves' : 'transitions';
        label = output.role === 'resolved-question' ? 'resolves' : output.role === 'partially-resolved-question' ? 'partially resolves' : 'advances';
      }

      visibleRelationships.push({
        id: `rel:visible:out:${experiment.slug}:${output.id}`,
        kind: isTransition ? 'transition' : 'experiment-to-output',
        scope: 'visible',
        from: expEntity,
        to: output.entity,
        edgeType,
        label,
        basis: 'relatedFindings / relatedQuestions',
        detail: `${output.entity.id} is registered against this experiment`,
        shownInMap: true,
      });
    }
  }

  // ── Additional relationships ──────────────────────────────────────────
  const additionalRelationships: InOutRelationship[] = [];
  const inputEntityIds = new Set(inputs.map((i) => i.entity.id));
  const outputEntityIds = new Set(outputs.map((o) => o.entity.id));

  for (const edge of edges) {
    const fromIn = inputEntityIds.has(edge.src) || outputEntityIds.has(edge.src) || edge.src === experiment.slug;
    const toIn = inputEntityIds.has(edge.dst) || outputEntityIds.has(edge.dst) || edge.dst === experiment.slug;
    if (!fromIn || !toIn) continue;

    if (edge.src === experiment.slug || edge.dst === experiment.slug) {
      if (visibleRelationships.some((r) => r.from.id === edge.src && r.to.id === edge.dst)) continue;
      if (visibleRelationships.some((r) => r.from.id === edge.dst && r.to.id === edge.src)) continue;
    }

    const fromEntity = resolveEntityStrict(edge.src, findings, openQuestions, experiments);
    const toEntity = resolveEntityStrict(edge.dst, findings, openQuestions, experiments);

    const isVisible = fromEntity.kind !== 'unknown' && toEntity.kind !== 'unknown' &&
      (inputEntityIds.has(fromEntity.id) || outputEntityIds.has(fromEntity.id) || fromEntity.id === experiment.slug) &&
      (inputEntityIds.has(toEntity.id) || outputEntityIds.has(toEntity.id) || toEntity.id === experiment.slug);

    additionalRelationships.push({
      id: `rel:extra:${edge.src}:${edge.edgeType}:${edge.dst}`,
      kind: isVisible ? 'cross-link' : 'external',
      scope: fromEntity.kind === 'unknown' || toEntity.kind === 'unknown' ? 'unresolved' : isVisible ? 'visible' : 'external',
      from: fromEntity, to: toEntity,
      edgeType: edge.edgeType,
      label: EDGE_TYPE_LABEL[edge.edgeType] ?? 'relates to',
      basis: edge.basis, detail: edge.detail,
      shownInMap: isVisible,
    });
  }

  return {
    experiment: buildExperimentVm(experiment),
    inputs, outputs,
    relationships: [...visibleRelationships, ...additionalRelationships],
    visibleRelationships,
    additionalRelationships,
  };
}

function emptyViewModel(): InOutViewModel {
  return { experiment: null, inputs: [], outputs: [], relationships: [], visibleRelationships: [], additionalRelationships: [] };
}

export function getSummary(vm: InOutViewModel): InOutSummary {
  return {
    inputs: vm.inputs.length,
    newFindings: vm.outputs.filter((o) => o.group === 'new-findings').length,
    newQuestions: vm.outputs.filter((o) => o.group === 'new-questions').length,
    updatedFindings: vm.outputs.filter((o) => o.group === 'updated-findings').length,
    resolvedQuestions: vm.outputs.filter((o) => o.group === 'resolved-questions').length,
    carriedForward: vm.outputs.filter((o) => o.group === 'carried-forward').length,
    artifacts: vm.outputs.filter((o) => o.group === 'artifacts').length,
    generatedReport: vm.outputs.some((o) => o.group === 'generated-report'),
    connections: vm.visibleRelationships.length,
  };
}

// ── Entity resolver (strict) ────────────────────────────────────────────

export function resolveEntityStrict(id: string, findings: Finding[], openQuestions: OpenQuestion[], experiments: Experiment[]): InOutEntity {
  if (id.startsWith('F-')) {
    const f = findings.find((x) => x.id === id);
    return f ? findingAsEntity(f) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('Q-')) {
    const q = openQuestions.find((x) => x.id === id);
    return q ? questionAsEntity(q) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('experiments/')) {
    const e = experiments.find((x) => x.slug === id);
    return e ? experimentAsEntity(e) : { id, kind: 'unknown', title: id, unresolved: true };
  }
  if (id.startsWith('input:finding:')) {
    const fid = id.replace('input:finding:', '');
    const f = findings.find((x) => x.id === fid);
    return f ? findingAsEntity(f) : { id: fid, kind: 'unknown', title: fid, unresolved: true };
  }
  if (id.startsWith('input:question:')) {
    const qid = id.replace('input:question:', '');
    const q = openQuestions.find((x) => x.id === qid);
    return q ? questionAsEntity(q) : { id: qid, kind: 'unknown', title: qid, unresolved: true };
  }
  if (id.startsWith('output:finding:')) {
    const fid = id.replace('output:finding:', '');
    const f = findings.find((x) => x.id === fid);
    return f ? findingAsEntity(f) : { id: fid, kind: 'unknown', title: fid, unresolved: true };
  }
  if (id.startsWith('output:question:')) {
    const qid = id.replace('output:question:', '');
    const q = openQuestions.find((x) => x.id === qid);
    return q ? questionAsEntity(q) : { id: qid, kind: 'unknown', title: qid, unresolved: true };
  }
  return { id, kind: 'unknown', title: id, unresolved: true };
}
